FROM ruby:2.7.3-alpine3.13

ENV LANG C.UTF-8
RUN apk upgrade && \
    apk add --no-cache \
    bash \
    build-base \
    curl-dev \
    git \
    graphviz \
    imagemagick \
    imagemagick-dev \
    less \
    libxml2-dev \
    libxslt-dev \
    mysql-client \
    mysql-dev \
    nodejs \
    openssl \
    readline \
    readline-dev \
    tar \
    ttf-freefont \
    tzdata \
    udev \
    wget \
    yarn \
    yaml \
    yaml-dev \
    vim \
    zlib \
    zlib-dev


# -------------------------------------------------

ENV APP_HOME /matsuhub-backend
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV GEM_HOME=/bundle

ADD Gemfile* $APP_HOME/

ENV BUNDLE_GEMFILE=$APP_HOME/Gemfile \
  BUNDLE_JOBS=4 \
  BUNDLE_PATH=$GEM_HOME

RUN gem install bundler
RUN bundle config set force_ruby_platform true
RUN gem update
RUN bundle install

ADD . $APP_HOME
ENV RAILS_ENV=staging
ENV RDS_DB_NAME=$RDS_DB_NAME
ENV RDS_PASSWORD=$RDS_PASSWORD
ENV RDS_HOSTNAME=$RDS_HOSTNAME
ENV RDS_PASSWORD=$RDS_PASSWORD
ENV RDS_PORT=$RDS_PORT
ENV S3_AWS_ACCESS_KEY_ID=$S3_AWS_ACCESS_KEY_ID
ENV S3_AWS_SECRET_ACCESS_KEY=$S3_AWS_SECRET_ACCESS_KEY
ENV API_DOMAIN=$API_DOMAIN
ENV API_HOST=$API_HOST
ENV MAILER_SENDER=$MAILER_SENDER
ENV SES_ACCESS_KEY_ID=$SES_ACCESS_KEY_ID
ENV SES_SECRET_ACCESS_KEY=$SES_SECRET_ACCESS_KEY

COPY ./services.sh /matsuhub-backend/scripts/
RUN chmod +x /matsuhub-backend/scripts/services.sh

CMD ["/matsuhub-backend/scripts/services.sh"]
