version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "4306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./mysqlconf:/etc/mysql/conf.d
  api:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - matsuhub-backend-image-cache
      args:
        ARG_RUBY_VERSION: ${ARG_RUBY_VERSION:-3.1.2}
    image: matsuhub-backend-image:0.0.1
    environment:
      - EDITOR=vim
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - ./:/matsuhub-backend
      - bundle:/bundle
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    tty: true
    stdin_open: true
volumes:
  db-data:
    driver: local
  bundle:
    driver: local
