name: Rails CI/CD

on:
  push:
    branches: chore/setting-github-actions2

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        docker-compose build
        docker-compose run api rails db:create
      env:
        RAILS_ENV: test
    - name: Rspec
      run:  |
        docker-compose run api bundle exec rspec
      env:
        RAILS_ENV: test
